### ISSUE TITLE
Xbox Live names with spaces fail

### ISSUE THREAD

**Issue by RubedoHawk** [BinarMorker/TimeWastedOnDestiny#1]
For any Xbox live username with spaces the lookup fails.

**Comment by BinarMorker** [comment]
I have not been able to reproduce this bug. I tried with the account 'Deej BNG'.Could you please give me a case where this happen?

**Comment by BinarMorker** [comment]
I was able to reproduce the bug and it should be fixed now. Let me know if it happens again!
