### ISSUE TITLE
Fatal error on Wasted on Destiny search

### ISSUE THREAD

**Issue by DMC4Dante360** [BinarMorker/TimeWastedOnDestiny#10]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /home/wod/public_html/request.php on line 331

Username on both PS4 and Xbox is DMC4Dante360.

**Comment by BinarMorker** [comment]
Issue fixed as of commit [#061c3e8](https://github.com/BinarMorker/TimeWastedOnDestiny/commit/061c3e83247de619dd86aefe0d772e41c2946cf0).
