### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by Slickrick876** [BinarMorker/TimeWastedOnDestiny#11]
The screen gets stuck in a loading loop when searching for any name.

**Comment by gho-ramos** [comment]
Same problem here, keep "Loading..."; PSN Tagname - RoyalTingles

**Comment by Mulchman** [comment]
Same. Things get stuck at loading. I even turned off ad-block in case that mattered.

**Comment by BinarMorker** [comment]
Issue fixed as of commit [#061c3e8](https://github.com/BinarMorker/TimeWastedOnDestiny/commit/061c3e83247de619dd86aefe0d772e41c2946cf0).
