### ISSUE TITLE
PSN username doesn't work

### ISSUE THREAD

**Issue by proper13** [BinarMorker/TimeWastedOnDestiny#13]
Nothing happens when I type my PSN username in to the search field. My PSN is P2thaR_O.

**Comment by DemonickAngelick** [comment]
Same. PSN: DemonickAngelick.

**Comment by BinarMorker** [comment]
Everything works on my end with your usernames. Can you send me a screenshot on your end?

**Comment by JoeyLFCrogerS** [comment]
I click submit and like the peeps have previously stated nothing happens. the leaderboard merely flashes and that is all.

**Comment by BinarMorker** [comment]
On what browser are you? Maybe try refreshing your browser?

**Comment by JoeyLFCrogerS** [comment]
I am on Chrome, I will try that and let you know.

**Comment by JoeyLFCrogerS** [comment]
I tried restarting my browser and got the same result, pressed playstation, then typed in my PSN JosusChristo. The leaderboard flashed and reappeared and that is all.

**Comment by beardo877** [comment]
Yup, same issue here. PSN: beardo877. I've tried Chrome and Safari using the Search feature, and plugging my name directly into the URL. When I do a search, the site flashes and the comes back with nothing in the white space. When I plug into the URL, I get two Leaderboards, but again, nothing in the white space. I'm uploading a 30 second video of my actions in Safari, but the same stuff was happening in Chrome.
[WoDScreen.mov.zip](https://github.com/BinarMorker/TimeWastedOnDestiny/files/103301/WoDScreen.mov.zip)

**Comment by JoeyLFCrogerS** [comment]
Funnily enough, after trying a couple of different things, I decided to simply type my PSN without the capitals and it worked! Thanks for your assistance, not sure if I'm happy with what I found out haha but I know how much time I've spent on Destiny now :')

**Comment by BinarMorker** [comment]
I seem to have resolved the issue with the last commit. Please refresh your browser and try again.

**Comment by Slickrick876** [comment]
Every one of those names work using firefox, chrome, and internet explorer.  Seems like you fixed the issue BinarMorker.  Great job as usual :)
