### ISSUE TITLE
Meaning of number displayed to the right of time played in red is unclear.

### ISSUE THREAD

**Issue by DavidBarry** [BinarMorker/TimeWastedOnDestiny#15]
I'm guessing that it may be referring to idle time in the game, but it's unclear. Mentioning it's meaning in the FAQ that appears directly below would certainly help clear that up.

**Comment by Slickrick876** [comment]
The red number on the side is the total amount of time for your deleted characters

**Comment by BinarMorker** [comment]
This has been fixed in the latest release. The time in red now has the word "deleted" after it
