### ISSUE TITLE
Stats vanished, HELP

### ISSUE THREAD

**Issue by LightUmUpBeast** [BinarMorker/TimeWastedOnDestiny#16]
Hiya,

I check my stats regularly and recently my stats changed to 0 hrs played, 0 characters created, top 100%, when I was top 1% before . Can you look into this please as there's nowhere else I can check my acc Inc deleted characters.

I play on PSN and my name is LightUmUpBeast 

Cheers,

Stu

**Comment by LightUmUpBeast** [comment]
Still nothing, my character and emblem appear, but shows as 0 characters created or deleted :(

**Comment by BinarMorker** [comment]
I'm looking for a fix. It seems that I can only replicate the bug on the website, online. My local website works normally. I'll look further.

**Comment by LightUmUpBeast** [comment]
Thank you :)

**Comment by LightUmUpBeast** [comment]
Still no fix :(

**Comment by BinarMorker** [comment]
I am sorry. I've just begun an internship so I'm not on the issue as often as I'd need to be. This is my priority for the website, and I did not forget you, rest assured!

**Comment by LightUmUpBeast** [comment]
Thankyou :)

**Comment by BinarMorker** [comment]
This should be fixed now. Tell me if it works in a few hours to allow the cache to refresh.

**Comment by LightUmUpBeast** [comment]
Cheers François.  I just got the closed email so checked and it says I
don't exist

**Comment by BinarMorker** [comment]
That's normal. Just wait an hour or two and it should fix itself.

**Comment by LightUmUpBeast** [comment]
Still says does not exist :(

**Comment by BinarMorker** [comment]
Did you try clearing the cache of your browser? You can also try accessing
the website on another computer.

On my end, I got the right result without touching anything. The fix I
deployed yesterday made your account work on the website now.

**Comment by LightUmUpBeast** [comment]
Worked a treat, thankyou :))
