### ISSUE TITLE
Usernames with space won't work

### ISSUE THREAD

**Issue by ninjaunova** [BinarMorker/TimeWastedOnDestiny#17]
On your website the username Ninja Unova does not work, that is my gamer tag on Xbox. If it is my fault please let me know, thank you.

**Comment by Youmy001** [comment]
It looks like there's an issue with blank spaces in display names. I tried removing the space and it worked.

http://wastedondestiny.com/api/?console=1&user=NinjaUnova&fmt

**Comment by SS-Camaro** [comment]
My username on XB Live is "SS Camaro". Pulls up "SScamaro" on PS4.....

**Comment by BinarMorker** [comment]
It works okay on my end, you just have to search your name in the Xbox searchbox.
If the issue is really that another user is being shown when we search your username under a different platform, then it was made like that by design. Sorry about that :)
