### ISSUE TITLE
My username does not work!

### ISSUE THREAD

**Issue by NotoriousStormtrooper** [BinarMorker/TimeWastedOnDestiny#18]
I recently changed my username, and now this site doesn't work for me anymore. It's getting quite annoying, is there a fix for this?

**Comment by Slickrick876** [comment]
You will need to include your username to have this looked at

**Comment by BinarMorker** [comment]
Please write me your old and new username and I'll check this out.

**Comment by marm0lade** [comment]
My username does not seem to work. I have tried on multiple browsers on multiple PCs. I get the spinning loading symbol but it never completes. Username: marmo7ade

**Comment by BinarMorker** [comment]
Please see issue #19 .

The website is currently down. Please allow for a few days so I can have everything sorted out. Thank you.

**Comment by BinarMorker** [comment]
@marm0lade Now that the website is back online, your username seems to work again. Sorry for the inconvenient!
