### ISSUE TITLE
Second account not showing

### ISSUE THREAD

**Issue by Slickrick876** [BinarMorker/TimeWastedOnDestiny#22]
I have an Xbox account linked to my profile in addition to my PSN profile and it isn't showing the time on this site.
PSN:  G-Money876
XBL:  GMoney0876

**Comment by BinarMorker** [comment]
There, it should be fixed now.

**Comment by Maschingon** [comment]
Do you just sit there and play story mode on the dark within or do you do anything else?

**Comment by BinarMorker** [comment]
Hi @Maschingon , I think this would be better to discuss this in private with him. Please keep this place clean for issues on the website or the API. Thanks.
