### ISSUE TITLE
username not found

### ISSUE THREAD

**Issue by lostsoul135** [BinarMorker/TimeWastedOnDestiny#26]
my user is lostsoul_135. On Bungie I can find each individual character's hours, but was looking for a complete breakdown

thanks

**Comment by BinarMorker** [comment]
It seems to be working now. Maybe Bungie had a maintenance. Did you do anything?

**Comment by lostsoul135** [comment]
That's very odd. It comes up as an xbox user, when it's a ps4 user. No worries though, it still looks correct.
Thanks for your help!
