### ISSUE TITLE
P4DR1N00 for PS4 doesn't work.

### ISSUE THREAD

**Issue by P4DR1N00** [BinarMorker/TimeWastedOnDestiny#27]
P4DR1N00 for PS4 doesn't work.

**Comment by BinarMorker** [comment]
Does it work now? There was a maintenance for the stats section on Bungie.net last week.

**Comment by P4DR1N00** [comment]
Yes now it works. thank you

**Comment by P4DR1N00** [comment]
Yes now it works. Thank You
