### ISSUE TITLE
Gamertag not displaying correctly in middle box: "Total time spent"

### ISSUE THREAD

**Issue by tlyon926** [BinarMorker/TimeWastedOnDestiny#3]
My xbox gamertag is cyclone926 if you would like to check this out yourself. The username displays properly in the xbox (far right) box, but the the middle box it removes a letter in my username. Instead of displaying "cyclone926", it shows "cyclon926"-- it removes the "e" from my username.

Also, I believe there might be an issue with the number that it displays for my total time spent playing. If you check on destiny tracker (link: http://destinytracker.com/destiny/player/xbox/cyclone926) and on destiny db (link: http://www.destinydb.com/guardians/xbox/2305843009230128132-cyclone926) it shows my total playing time as (if you combine all my characters) approximately 230 hours. But on your website (link: http://wastedondestiny.com/playstation/cyclon926) it shows my total as 162 hours. I realize it doesn't include any idle time, but a 70 hour difference seems a bit off to me. Maybe it's normal, but it may be worth a check.

**Comment by BinarMorker** [comment]
Thank you for the feedback! You are right, your middle display name is missing an "E". That is not on my end though, but in the way you have typed your display name on Bungie's website. If you check your profile [here](https://www.bungie.net/en/Profile/254/1092237), you can see that your Bungie name is missing an "E", but your gamertag has it.

Also, a 70 hour difference is nothing unusual. You would be surprise how many people get at least half their time removed!

**Comment by tlyon926** [comment]
Thanks for the quick response, I just fixed my username on bnet (I wonder how long it had been incorrect, weird!). I just retried entering it in the site, but it still displays incorrectly. I'm guessing that it just needs some time to refresh or reload; I'll be sure to leave some more feedback if it doesn't correct itself in a few days or so.

Anyway, keep up the good work on the website!

**Comment by BinarMorker** [comment]
Just try again in an hour and it will fix itself!
