### ISSUE TITLE
Xbox one account - legacy error

### ISSUE THREAD

**Issue by ashrasputin** [BinarMorker/TimeWastedOnDestiny#30]
Hello, 

I play on xbox one but when i put in my gamertag i get the error that i am on legacy console. 

Gamertag : Ash Rasputin

**Comment by TronieNZ** [comment]
I have the same issue. Legacy PSN on PS3 but I started on Xbox 360, moved to XB1, have used this website in the past but getting the legacy message for some time now using my XB GT

**Comment by Youmy001** [comment]
@ashrasputin We tried and your gamertag works fine.
@TronieNZ What is your gamertag?

**Comment by TronieNZ** [comment]
TronieNZ

**Comment by BinarMorker** [comment]
The bug is now fixed. https://www.wastedondestiny.com/xbox/tronienz
