### ISSUE TITLE
My account doesnt have enought time.

### ISSUE THREAD

**Issue by iFAboii** [BinarMorker/TimeWastedOnDestiny#31]
I have played Destiny since the alpha. And y1 y2 y3 almost every single day for minimum of 6h a day!?!

**Comment by BinarMorker** [comment]
It might be because the website only counts active playtime, not social
spaces or orbit time.

**Comment by BinarMorker** [comment]
Since there is no update, I will close this issue. If someone can prove that some accounts have a big difference in time than what is supposed to be shown, just let me know in this issue. Thanks.
