### ISSUE TITLE
Keep getting red bar when looking anyone up

### ISSUE THREAD

**Issue by bgrishinko** [BinarMorker/TimeWastedOnDestiny#32]
Getting the red bar saying to let you know there's an issue. Tried multiple web browsers and the app. Attached photo. Used one of the leaderboard players as an example.

![image](https://cloud.githubusercontent.com/assets/18425761/22400260/ce5d91d8-e57d-11e6-9eec-8e51eeef9bf0.png)

**Comment by BinarMorker** [comment]
This was a maintenance with Destiny.
