### ISSUE TITLE
Username doesn't load

### ISSUE THREAD

**Issue by LightUmUpBeast** [BinarMorker/TimeWastedOnDestiny#33]
For about the 5th time in the last year, my psn searches and doesn't show anything.

PSN LightUmUpBeast

Please help

**Comment by LightUmUpBeast** [comment]
28 days later and not even a reply. Damm the game really is dead

**Comment by BinarMorker** [comment]
Hey, sorry about that. Do you have more information on your account, or any suspected reason or particularity that would make it not work?

**Comment by Slickrick876** [comment]
Searching for that name results in 0h played.  There is at least 1 character associated with the account so it should yield some kind of result.
