### ISSUE TITLE
CORS headers for the API

### ISSUE THREAD

**Issue by remybach** [BinarMorker/TimeWastedOnDestiny#34]
Hey there,

I'm trying to use the API within a simple single page app which means making the API call from the front end. I was wondering whether - since it's a public API - you could make it return CORS headers?

Thanks for providing an API by the way! Not enough devs are willing to do this these days 👍

**Comment by BinarMorker** [comment]
Yeah no problem, I'll see if I can add CORS. I'll keep you updated when
it's done.

Thank you for being interested in my API!

**Comment by remybach** [comment]
Solved with #35.
