### ISSUE TITLE
Username used to show up now it doesn't. 

### ISSUE THREAD

**Issue by lejohnduke** [BinarMorker/TimeWastedOnDestiny#36]
basically what the title says my xbox gamertag used to work on this site when i searched but now i don't get any result

**Comment by BinarMorker** [comment]
What is your username?

**Comment by lejohnduke** [comment]
lejohnduke
For Both consoles

**Comment by BinarMorker** [comment]
The issue should now be fixed. Please confirm.

**Comment by lejohnduke** [comment]
still not working

**Comment by BinarMorker** [comment]
Alright, there has been a regression on the production environment. I'll
keep you informed when I'm able to update my website properly.

**Comment by Youmy001** [comment]
I looked as the issue and as @BinarMorker said it works, but it only works on the API as shown over here ([https://www.wastedondestiny.com/api/?console=1&user=lejohnduke](https://www.wastedondestiny.com/api/?console=1&user=lejohnduke)). However, there is an error while trying to load the information on the website.

The error thrown is a "Cannot read property 'forEach' of undefined" on line 74 of viewmodel.js. Althought @lejohnduke have an account for PS4, he might have never created a character on that account in Destiny. @BinarMorker, you  should verify `characters` exists in `self.player().playstation` and `self.player().xbox` beforre looping inside them.

**Comment by BinarMorker** [comment]
I figured this out already and corrected the issue. However, I could not
deploy yet.

**Comment by BinarMorker** [comment]
A fix has been deployed.

**Comment by lejohnduke** [comment]
thank you all for your help!
