### ISSUE TITLE
My hours are wrong

### ISSUE THREAD

**Issue by TheGunsmithUK** [BinarMorker/TimeWastedOnDestiny#38]
your site says I have 5637 hrs on Destiny ..... my xbox tells me I have 13500+ hrs on destiny .... are you suggesting that I have spent 8000hrs in the tower or in orbit ???? suggest you check your system, it is a total failure...

**Comment by BinarMorker** [comment]
When I'm counting the time you've played on all your characters, I get 3462 hours. This data is taken straight from Bungie's website: https://www.bungie.net/en/Stats/1/4611686018429585192/2305843009285025843?mode=all

Titan - 58d 11h 49m
Warlock - 79d 13h 58m
Hunter - 6d 4h 0m

My website pulls this data and included deleted characters (2175 hours), for a total of 5637 hours.

I'm not saying your Xbox is wrong, but if my website is wrong, so is Bungie's. My hypothesis is that every second your game is open, even if you're on the title screen, or loading, in orbit, switching characters, getting an error or playing, it logs your time and that makes your time played seem much bigger than it really is.

I hope I answered your question!

**Comment by TheGunsmithUK** [comment]
Every moment I spend logged into Destiny is time spent playing the game, I am not playing anything else but Destiny, even the numbers you just quoted are inaccurate, your logic is inaccurate, if I am switching characters, or waiting for matchmaking to complete, I am still playing Destiny .... your stats and logic are so flawed it's laughable ..... you have taken a set of numbers and created what is in effect   3+3=5 or perhaps its 7, who knows, your formula is a joke ...

**Comment by BinarMorker** [comment]
Have you checked on Bungie.net? This is where the data is pulled.

**Comment by BinarMorker** [comment]
As for the rest of the time when you are playing, Xbox may be your most precise metric for how much time you had the game opened. Waiting for matchmaking or in orbit is not calculated on Bungie's end, so I can't access this data and add it to the rest. Sorry about that!

On a different note, I would appreciate if you would keep this kind of language to yourself. I am only trying to help you here. Attacking me or how my website is made won't get us anywhere.
