### ISSUE TITLE
Username not working

### ISSUE THREAD

**Issue by Ethelith** [BinarMorker/TimeWastedOnDestiny#40]
I was able to see my Destiny 1 account fine up until a day or so ago. Now it just says “no account found” even though I’d previously used it.
Also, when I could check it previously the Destiny 2 one wouldn’t load. It would just say there was an error and disappear.

Thanks for this! It’s honestly great and so much fun to actually see how many hours I’ve played. =)

**Comment by BinarMorker** [comment]
Thank you very much, it means a lot to me that you like my website :)

Could you retry now to see if it works? Bungie had a maintenance or something earlier.

**Comment by BinarMorker** [comment]
I tried Ethelith and it seemed to work correctly. If it's not your username I will investigate further. Otherwise, everything is good now.
