### ISSUE TITLE
D2 Times Not Showing

### ISSUE THREAD

**Issue by rusty022** [BinarMorker/TimeWastedOnDestiny#41]
My D2 times are not showing up. PSN is Rusty022, and Bungie.net is "Rusty"

**Comment by BinarMorker** [comment]
It looks like a timeout issue. I will look into this, thank you.

**Comment by BinarMorker** [comment]
#44

**Comment by BinarMorker** [comment]
It is working now.

**Comment by rusty022** [comment]
Works! Thanks!
