### ISSUE TITLE
Site fails to search in Edge

### ISSUE THREAD

**Issue by corsairmarks** [BinarMorker/TimeWastedOnDestiny#42]
Typing a username in the search box and either pressing the magnifying glass search button, or the enter key, fails to execute a search.

Also, goin to the correct url directly also fails to load data.

Ex:

My Xbox gamertag is `NikoRedux`.  It is associated to my Bungie account `corsairmarks`.  I am not redirected to the search url https://www.wastedondestiny.com/search/corsairmarks with the scenario described above.

**Comment by BinarMorker** [comment]
#43 This is linked to this issue
