### ISSUE TITLE
Destiny 2 player stats not loading

### ISSUE THREAD

**Issue by corsairmarks** [BinarMorker/TimeWastedOnDestiny#47]
Destiny 2 player stats don't seem to load. I'm unsure whether this is specific to me, or happening overall.

* Screenshot: https://www.screencast.com/t/O948nSeJmHW
* Browser: Chrome 62.0.3202.62 (64bit)
* Xbox Gamertag: NikoRedux

**Comment by BinarMorker** [comment]
Thank you very much for the info. I will check this ASAP!

**Comment by BinarMorker** [comment]
Everything seems to be working on my end. Would you please try again and tell me if it happens again? It might have been the cache.
