### ISSUE TITLE
Battlenet

### ISSUE THREAD

**Issue by mrrandomidea** [BinarMorker/TimeWastedOnDestiny#50]
When I search my battlenet name nothing shows up and just loads, I am including my full battletag and when I search my friends battletag theirs shows up. I have it linked to bungie if that matters.

**Comment by BinarMorker** [comment]
Cound you please specify your username to me? You can do it privately on my personal email if you wish. binarmorker@gmail.com

**Comment by mrrandomidea** [comment]
Ideas#11399 is my battletag

**Comment by BinarMorker** [comment]
I have fixed the issue now. Thank you very much for reporting this bug!
