### ISSUE TITLE
Battlenet account not working

### ISSUE THREAD

**Issue by Aertheos** [BinarMorker/TimeWastedOnDestiny#52]
Hi, I tried searching up my battlenet id (Aertheos#1941) and I couldn't get anything to show up. I tried my friends accounts, and it worked fine, but I can't do it with mine.

**Comment by BinarMorker** [comment]
I'm currently working on improvements on Battle.net account handling, so I will look into this issue at the same time. Thank you.

**Comment by BinarMorker** [comment]
It is working on my end. Maybe you tried just before I pushed my latest update and the cache did not refresh yet. Anyways, it should be all good now. Thank you for your patience.
