### ISSUE TITLE
Battlenet Account Not Working (Possibly due to unsupported characters)

### ISSUE THREAD

**Issue by cburj** [BinarMorker/TimeWastedOnDestiny#53]
Battle Tag is cbürg#2114

I'm assuming that the ü is causing the problem.

**Comment by BinarMorker** [comment]
It seems that battle tags with unicode characters don't work with either my search function or Bungie's search function. It might be something on their end. I will check.

**Comment by BinarMorker** [comment]
https://github.com/Bungie-net/api/issues/266

**Comment by BinarMorker** [comment]
The problem is now fixed.
