### ISSUE TITLE
Leaderboard/Rank

### ISSUE THREAD

**Issue by Slickrick876** [BinarMorker/TimeWastedOnDestiny#7]
The leader board and just ranks in general are not updating correctly.  I've looked up names that had many less hours, but were a higher rank than me.  And the top 10 leader board hasn't update correctly.  The number 2 player has hundreds of hours more than the current number by the time played on here.

**Comment by Youmy001** [comment]
Can you give us example of users with their name and time so we can investigate the issue?

**Comment by Slickrick876** [comment]
PeppenServos LG   (XBOX)  is currently showing at number 1.  Those hours actually updated on the board.  Policemam (PSN) is showing number 2, but has over 300 more hours played and these hours are not updating on the leader board.  Neither of those are mine, but my hours are catching up with them pretty quickly.  I hope this makes sense.

**Comment by Slickrick876** [comment]
I have no idea what you guys did, but it seems to be working now.  I moved up to 209 from nearly 2800.
