### ISSUE TITLE
Username Not Working

### ISSUE THREAD

**Issue by blackph0enix** [BinarMorker/TimeWastedOnDestiny#8]
Went to use the site, and it just says "Account not found". My GT is: Young Hurt

**Comment by BinarMorker** [comment]
It should be fixed now.

**Comment by blackph0enix** [comment]
I'm still having the same issue.

**Comment by blackph0enix** [comment]
![screenshot 2015-09-24 20 07 46](https://cloud.githubusercontent.com/assets/5624065/10090002/0729e69c-62f8-11e5-8c4c-838292da8760.png)

**Comment by BinarMorker** [comment]
I can see the problem, thank you. Does your account have any particularity?

**Comment by blackph0enix** [comment]
No it does not.
On Fri, Sep 25, 2015 at 07:05 François Allard <notifications@github.com>
wrote:

> I can see the problem, thank you. Does your account have any particularity?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BinarMorker/TimeWastedOnDestiny/issues/8#issuecomment-143188095>
> .
>
-- 
Very Respectfully,


Christopher Battle

**Comment by BinarMorker** [comment]
I'm sorry for the wait. Please test it for yourself to see if it works correctly.

**Comment by blackph0enix** [comment]
It is working now, thank you!
On Fri, Sep 25, 2015 at 20:34 François Allard <notifications@github.com>
wrote:

> I'm sorry for the wait. Please test it for yourself to see if it works
> correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BinarMorker/TimeWastedOnDestiny/issues/8#issuecomment-143384001>
> .
>
-- 
Very Respectfully,


Christopher Battle

**Comment by T-Mac2467** [comment]
my friends PSN ID of General_Vexx doesn't work

**Comment by BinarMorker** [comment]
From what I see, this account has never played Destiny on PS3 or PS4. Could that be an error in the PSN id?

**Comment by BinarMorker** [comment]
[This website](http://psnprofiles.com/general_vexx) does not show any records of him playing Destiny, nor does searching his name on Bungie give any results.
